spring.application.name=spring_testing_api

spring.security.user.name=admin
spring.security.user.password=123456

spring.datasource.url=jdbc:postgresql://localhost:5432/dbpos
spring.datasource.username=postgres
spring.datasource.password=admin123
# spring.datasource.driver-class-name=org.postgresql.Driver


# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# spring.jpa.open-in-view=false

# 1-based pagination (page=1 is the first page)
spring.data.web.pageable.one-indexed-parameters=true

# using redis
spring.data.redis.host=127.0.0.1
spring.data.redis.port=6379

# rabbit mq
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

